"""empty message

Revision ID: faf37a7586d8
Revises: bbdb0f545caa
Create Date: 2023-06-17 16:55:18.369284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faf37a7586d8'
down_revision = 'bbdb0f545caa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(length=255), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firstName', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('lastName', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('role', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    with op.batch_alter_table('leaves', schema=None) as batch_op:
        batch_op.drop_column('lastName')
        batch_op.drop_column('firstName')

    # ### end Alembic commands ###
